/* SpecView.c -- !RTLSDRView: a live spectrum display for the RTL-SDR
   RISC OS driver. Phase 2, milestone 1 (see ../../../docs/PLAN.md):
   proves the architecture (continuous USB reads inside a Wimp idle
   handler without freezing the desktop, an FFT, and a redraw loop) that
   everything after this builds on. No demodulation, no audio, no tuning
   UI yet -- fixed at 97.4MHz (FM broadcast band), 2.4 MSPS.

   Device bringup (find_device, baseband/tuner init, sample rate, raw
   OS_Find/OS_GBPB stream I/O) reuses c/Driver.c -- the same code proven
   across !RTLSDR's milestones 1-4, not reimplemented here.

   No Templates-editor GUI is available in this environment, so the
   window is built programmatically (a hand-filled window_block passed
   to Wimp_CreateWindow), not loaded from a template file.

   The FFT itself still avoids any libm call (sqrt/sin/cos/log): its
   twiddle table is precomputed offline (matches upstream reasoning for
   avoiding runtime trig -- see R82XX.c's sigma-delta PLL loop comments).
   The display SCALE, though, does call log10() (see compute_spectrum) --
   a first real run with a purely linear/rational power scale showed why
   that's not optional here: RTL-SDR's classic DC-spike artifact sits
   40-60dB above the noise floor (10^4-10^6x in raw power), which no
   single linear-ish curve can show alongside the noise floor without one
   end vanishing or the other saturating (confirmed: it did exactly that,
   twice, with two different linear-family scales -- see docs/PLAN.md).
   log10() was avoided in the very first version purely because runtime
   libm CALLS (distinct from +,-,*,/ on doubles, which were already
   confirmed working via Driver.c's sample-rate math) were unconfirmed
   against this toolchain's link setup -- resolved by just trying it
   through the build service, which would fail at LINK time with a clear
   "undefined symbol" if unavailable, rather than needing a hardware
   round-trip to find out.

   C89 only (Norcroft): all declarations at top of block, no // comments. */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "DeskLib:Core.h"
#include "DeskLib:Wimp.h"
#include "DeskLib:WimpSWIs.h"
#include "DeskLib:Window.h"
#include "DeskLib:Event.h"
#include "DeskLib:GFX.h"
#include "DeskLib:Time.h"
#include "RTLSDR.h"
#include "R82XX.h"
#include "Driver.h"

/* ---- FFT / spectrum geometry ----
   256-point complex FFT. Reading exactly one frame (256 complex I,Q byte
   pairs = 512 bytes) per os_gbpb_read4() call matches one of the sizes
   milestone 4's sweep proved fully reliable (64/128/256/512/1024 bytes
   all 5/5 instant; 2048 blocked ~110s) -- deliberately staying inside
   that known-safe boundary rather than picking an arbitrary frame size. */
#define FFT_SIZE      256
#define NUM_BINS      FFT_SIZE   /* one bar per complex output bin --
                                     covers the full -Fs/2..+Fs/2 range,
                                     not just half (unlike a real-input
                                     FFT), since our input is complex I/Q */
#define IQ_BYTES      (FFT_SIZE * 2)

#define BIN_WIDTH_OS  2
#define WORK_WIDTH    (NUM_BINS * BIN_WIDTH_OS)  /* 512 OS units */
#define WORK_HEIGHT   300                        /* OS units */

/* Redraw throttle, separate from how aggressively Null_spectrum drains
   the USB stream (see MAX_READ_ATTEMPTS there) -- redraw only every
   UPDATE_INTERVAL_CS centiseconds so a plain full-window repaint at
   native Wimp_Poll rate doesn't waste CPU/flicker. */
#define UPDATE_INTERVAL_CS 20   /* ~5Hz redraw */

/* finalize_display() auto-scales the (now power-averaged) min/max dB
   range to
   the window height, rather than using a fixed DB_FLOOR/DB_CEIL -- three
   iterations of guessing a fixed range (see docs/PLAN.md) kept failing
   because the right constant depends on absolute signal strength, which
   varies with antenna/location/gain and can't be picked correctly in
   advance. Real spectrum analyzers auto-scale their Y-axis for the same
   reason. DC_EXCLUDE_BINS excludes the bins right around the display
   centre (where the FFT-shift places 0Hz/DC) from that min/max
   calculation: RTL-SDR's DC-spike artifact is a hardware/ADC artifact,
   not received signal, and including it would let it dominate the range
   and crush everything else back toward zero -- exactly what a fixed
   DB_CEIL guess kept doing anyway. The DC bin itself is still PLOTTED
   (just not used to pick the scale), so it'll typically still show as a
   tall/clipped spike, same as real SDR software. */
#define DC_EXCLUDE_BINS 2

/* ---- twiddle table: cos/sin(-2*pi*k/FFT_SIZE), k=0..FFT_SIZE/2-1 ----
   Precomputed offline (Python), not generated by any runtime trig call. */
static const double twiddle_cos[FFT_SIZE / 2] = {
    1.0000000000, 0.9996988187, 0.9987954562, 0.9972904567,
    0.9951847267, 0.9924795346, 0.9891765100, 0.9852776424,
    0.9807852804, 0.9757021300, 0.9700312532, 0.9637760658,
    0.9569403357, 0.9495281806, 0.9415440652, 0.9329927988,
    0.9238795325, 0.9142097557, 0.9039892931, 0.8932243012,
    0.8819212643, 0.8700869911, 0.8577286100, 0.8448535652,
    0.8314696123, 0.8175848132, 0.8032075315, 0.7883464276,
    0.7730104534, 0.7572088465, 0.7409511254, 0.7242470830,
    0.7071067812, 0.6895405447, 0.6715589548, 0.6531728430,
    0.6343932842, 0.6152315906, 0.5956993045, 0.5758081914,
    0.5555702330, 0.5349976199, 0.5141027442, 0.4928981922,
    0.4713967368, 0.4496113297, 0.4275550934, 0.4052413140,
    0.3826834324, 0.3598950365, 0.3368898534, 0.3136817404,
    0.2902846773, 0.2667127575, 0.2429801799, 0.2191012402,
    0.1950903220, 0.1709618888, 0.1467304745, 0.1224106752,
    0.0980171403, 0.0735645636, 0.0490676743, 0.0245412285,
    0.0000000000, -0.0245412285, -0.0490676743, -0.0735645636,
    -0.0980171403, -0.1224106752, -0.1467304745, -0.1709618888,
    -0.1950903220, -0.2191012402, -0.2429801799, -0.2667127575,
    -0.2902846773, -0.3136817404, -0.3368898534, -0.3598950365,
    -0.3826834324, -0.4052413140, -0.4275550934, -0.4496113297,
    -0.4713967368, -0.4928981922, -0.5141027442, -0.5349976199,
    -0.5555702330, -0.5758081914, -0.5956993045, -0.6152315906,
    -0.6343932842, -0.6531728430, -0.6715589548, -0.6895405447,
    -0.7071067812, -0.7242470830, -0.7409511254, -0.7572088465,
    -0.7730104534, -0.7883464276, -0.8032075315, -0.8175848132,
    -0.8314696123, -0.8448535652, -0.8577286100, -0.8700869911,
    -0.8819212643, -0.8932243012, -0.9039892931, -0.9142097557,
    -0.9238795325, -0.9329927988, -0.9415440652, -0.9495281806,
    -0.9569403357, -0.9637760658, -0.9700312532, -0.9757021300,
    -0.9807852804, -0.9852776424, -0.9891765100, -0.9924795346,
    -0.9951847267, -0.9972904567, -0.9987954562, -0.9996988187
};

static const double twiddle_sin[FFT_SIZE / 2] = {
    -0.0000000000, -0.0245412285, -0.0490676743, -0.0735645636,
    -0.0980171403, -0.1224106752, -0.1467304745, -0.1709618888,
    -0.1950903220, -0.2191012402, -0.2429801799, -0.2667127575,
    -0.2902846773, -0.3136817404, -0.3368898534, -0.3598950365,
    -0.3826834324, -0.4052413140, -0.4275550934, -0.4496113297,
    -0.4713967368, -0.4928981922, -0.5141027442, -0.5349976199,
    -0.5555702330, -0.5758081914, -0.5956993045, -0.6152315906,
    -0.6343932842, -0.6531728430, -0.6715589548, -0.6895405447,
    -0.7071067812, -0.7242470830, -0.7409511254, -0.7572088465,
    -0.7730104534, -0.7883464276, -0.8032075315, -0.8175848132,
    -0.8314696123, -0.8448535652, -0.8577286100, -0.8700869911,
    -0.8819212643, -0.8932243012, -0.9039892931, -0.9142097557,
    -0.9238795325, -0.9329927988, -0.9415440652, -0.9495281806,
    -0.9569403357, -0.9637760658, -0.9700312532, -0.9757021300,
    -0.9807852804, -0.9852776424, -0.9891765100, -0.9924795346,
    -0.9951847267, -0.9972904567, -0.9987954562, -0.9996988187,
    -1.0000000000, -0.9996988187, -0.9987954562, -0.9972904567,
    -0.9951847267, -0.9924795346, -0.9891765100, -0.9852776424,
    -0.9807852804, -0.9757021300, -0.9700312532, -0.9637760658,
    -0.9569403357, -0.9495281806, -0.9415440652, -0.9329927988,
    -0.9238795325, -0.9142097557, -0.9039892931, -0.8932243012,
    -0.8819212643, -0.8700869911, -0.8577286100, -0.8448535652,
    -0.8314696123, -0.8175848132, -0.8032075315, -0.7883464276,
    -0.7730104534, -0.7572088465, -0.7409511254, -0.7242470830,
    -0.7071067812, -0.6895405447, -0.6715589548, -0.6531728430,
    -0.6343932842, -0.6152315906, -0.5956993045, -0.5758081914,
    -0.5555702330, -0.5349976199, -0.5141027442, -0.4928981922,
    -0.4713967368, -0.4496113297, -0.4275550934, -0.4052413140,
    -0.3826834324, -0.3598950365, -0.3368898534, -0.3136817404,
    -0.2902846773, -0.2667127575, -0.2429801799, -0.2191012402,
    -0.1950903220, -0.1709618888, -0.1467304745, -0.1224106752,
    -0.0980171403, -0.0735645636, -0.0490676743, -0.0245412285
};

/* ---- global state ---- */
static char device_name_g[16];
static int stream_handle_g = 0;
static unsigned char iq_frame_g[IQ_BYTES];
static unsigned char accum_buf_g[IQ_BYTES];
static int accum_fill_g = 0;
static int bin_height_g[NUM_BINS];
static unsigned int next_update_time_g;
static window_handle spectrum_window_g;

/* Diagnostic-only globals, drawn as a text line during redraw (see
   Redraw_spectrum). Originally added to chase down a real bug: DeviceFS
   pads short reads to the requested size in its default blocking mode
   (confirmed via real DeviceFS source, see docs/PLAN.md milestone 5),
   so os_gbpb_read4() used to claim a full transfer while genuinely
   writing only ~2 bytes. Fixed by enabling non-blocking mode
   (os_args_set_nonblocking) and accumulating its now-honest short reads
   into accum_buf_g instead of demanding a full IQ_BYTES every call.
   Left these counters in place -- still useful to see the pipeline is
   alive at a glance. */
static unsigned long debug_reads_ok_g = 0;
static unsigned long debug_reads_bad_g = 0;
static double debug_db_min_g = 0.0;
static double debug_db_max_g = 0.0;
static double debug_db_dc_g = 0.0;
static unsigned char debug_first_bytes_g[12];
static unsigned char debug_byte_min_g = 255;
static unsigned char debug_byte_max_g = 0;
static int debug_max_offset_g = 0;

/* ---- in-place iterative radix-2 DIT FFT, fixed N=FFT_SIZE ---- */
static void fft256(double *re, double *im)
{
    unsigned int i, j, k;
    unsigned int len, half, step;
    unsigned int bit;
    double tr, ti, wr, wi, ur, ui;

    /* bit-reversal permutation */
    j = 0;
    for (i = 0; i < FFT_SIZE - 1; i++) {
        if (i < j) {
            tr = re[i]; re[i] = re[j]; re[j] = tr;
            ti = im[i]; im[i] = im[j]; im[j] = ti;
        }
        bit = FFT_SIZE >> 1;
        while (j & bit) {
            j &= ~bit;
            bit >>= 1;
        }
        j |= bit;
    }

    /* iterative Cooley-Tukey, block length doubling each stage */
    for (len = 2; len <= FFT_SIZE; len <<= 1) {
        half = len >> 1;
        step = FFT_SIZE / len; /* stride into the full-size twiddle table */
        for (i = 0; i < FFT_SIZE; i += len) {
            for (k = 0; k < half; k++) {
                wr = twiddle_cos[k * step];
                wi = twiddle_sin[k * step];
                ur = re[i + k];
                ui = im[i + k];
                tr = re[i + k + half] * wr - im[i + k + half] * wi;
                ti = re[i + k + half] * wi + im[i + k + half] * wr;
                re[i + k] = ur + tr;
                im[i + k] = ui + ti;
                re[i + k + half] = ur - tr;
                im[i + k + half] = ui - ti;
            }
        }
    }
}

/* Converts the last-read I/Q frame to power-spectrum bar heights,
   FFT-shifted so the tuned frequency sits in the middle of the display
   (bin 0 of a complex FFT is 0Hz baseband; negative frequencies wrap to
   the upper half, so swapping halves gives the usual centred view).

   Split into two halves: accumulate_frame() FFTs one completed frame
   and folds its power into a running average (called every time
   Null_spectrum finishes a frame, which can happen many times a
   second -- much faster than the ~5Hz display rate); finalize_display()
   converts the current running average into bar heights (called only
   at the throttled display rate). Averaging happens in the POWER
   (linear) domain across many frames before ever taking a log, not by
   averaging dB values -- log of an average is not the same as an
   average of logs, and only power-domain averaging reduces a single
   raw FFT snapshot's high per-bin variance the way real spectrum
   analyzers' "trace averaging" does. A live run found the previous
   single-snapshot-per-display-update approach was detecting a real,
   rock-solid-consistent signal (proving genuine detection, not noise --
   see docs/PLAN.md) but measuring almost no contrast between it and
   the noise floor, which is consistent with exactly this kind of
   un-averaged periodogram variance, not a wiring bug. */

/* Smoothing factor for the exponential power average -- higher weights
   new frames more (faster response, less noise reduction), lower
   weights history more (slower response, more noise reduction). 0.05
   is a first-pass guess (~20-frame effective window), not measured. */
#define AVG_ALPHA 0.05

static double avg_power_g[NUM_BINS]; /* zero-initialized; power domain */

static void accumulate_frame(void)
{
    static double re[FFT_SIZE];
    static double im[FFT_SIZE];
    int i, src;
    double sum_re, sum_im, mean_re, mean_im, power;

    /* DC removal: subtract this FRAME'S OWN measured mean, not just the
       fixed assumed centre (127.5) -- see docs/PLAN.md for why a real
       hardware DC bias needs removing at the source (it spectrally
       leaks into nearby bins too, not just the exact centre one), not
       just excluded from the display-scale calculation. */
    sum_re = 0.0;
    sum_im = 0.0;
    for (i = 0; i < FFT_SIZE; i++) {
        sum_re += (double)iq_frame_g[2 * i] - 127.5;
        sum_im += (double)iq_frame_g[2 * i + 1] - 127.5;
    }
    mean_re = sum_re / (double)FFT_SIZE;
    mean_im = sum_im / (double)FFT_SIZE;
    for (i = 0; i < FFT_SIZE; i++) {
        re[i] = ((double)iq_frame_g[2 * i] - 127.5) - mean_re;
        im[i] = ((double)iq_frame_g[2 * i + 1] - 127.5) - mean_im;
    }

    fft256(re, im);

    for (i = 0; i < NUM_BINS; i++) {
        src = (i + NUM_BINS / 2) % NUM_BINS;
        power = re[src] * re[src] + im[src] * im[src];
        avg_power_g[i] = avg_power_g[i] * (1.0 - AVG_ALPHA) + power * AVG_ALPHA;
    }
}

static void finalize_display(void)
{
    static double db[NUM_BINS];
    int i;
    int centre;
    int max_bin;
    double scaled;
    double db_min, db_max, range;

    for (i = 0; i < NUM_BINS; i++) {
        /* Epsilon just needs to avoid log10(0) -- see docs/PLAN.md for
           why this must stay small (1e-6) rather than the +1.0 it used
           to be, which was harmless only while DC dominated everything
           by a factor of ~10^9 and became a real dynamic-range-crushing
           bug once that was fixed. */
        db[i] = 10.0 * log10(avg_power_g[i] + 1e-6);
    }

    /* Auto-scale to this frame's own dynamic range (see the
       DC_EXCLUDE_BINS comment above for why the DC bin is skipped
       here). If every non-DC bin happens to read identically (a truly
       flat/silent frame), range collapses to 0 -- floor it to avoid a
       divide-by-zero, which just means that frame draws as flat. */
    centre = NUM_BINS / 2;
    db_min = db[(centre + DC_EXCLUDE_BINS + 1) % NUM_BINS];
    db_max = db_min;
    max_bin = (centre + DC_EXCLUDE_BINS + 1) % NUM_BINS;
    for (i = 0; i < NUM_BINS; i++) {
        if (i >= centre - DC_EXCLUDE_BINS && i <= centre + DC_EXCLUDE_BINS) {
            continue;
        }
        if (db[i] < db_min) {
            db_min = db[i];
        }
        if (db[i] > db_max) {
            db_max = db[i];
            max_bin = i;
        }
    }
    range = db_max - db_min;
    if (range < 1.0) {
        range = 1.0;
    }

    debug_db_min_g = db_min;
    debug_db_max_g = db_max;
    debug_db_dc_g = db[centre];
    /* How many bins the frame's strongest (non-DC) point sits from the
       tuned frequency (dead centre after the FFT-shift). If this
       consistently lands somewhere within the ~21-bin span a 200kHz-
       wide FM signal should occupy (roughly +-10 of centre, at our
       ~9.4kHz/bin resolution), that's consistent with a real station
       peak; if it's scattered randomly across all 251 non-DC bins
       frame to frame, that points to noise-floor-driven behaviour with
       no real signal peak being captured. See docs/PLAN.md. */
    debug_max_offset_g = max_bin - centre;

    for (i = 0; i < NUM_BINS; i++) {
        scaled = (db[i] - db_min) / range * (double)WORK_HEIGHT;
        if (scaled > (double)WORK_HEIGHT) {
            scaled = (double)WORK_HEIGHT;
        }
        if (scaled < 0.0) {
            scaled = 0.0;
        }
        bin_height_g[i] = (int)scaled;
    }
}

static void cleanup_and_exit(void)
{
    if (stream_handle_g != 0) {
        os_find_close(stream_handle_g);
        stream_handle_g = 0;
    }
    Event_CloseDown(); /* calls exit(); does not return */
}

static void report_and_die(const char *msg)
{
    os_error err;

    err.errnum = 1;
    strncpy(err.errmess, msg, sizeof(err.errmess) - 1);
    err.errmess[sizeof(err.errmess) - 1] = '\0';
    Wimp_ReportError(&err, 0, "RTLSDRView");
    exit(1);
}

static BOOL Null_spectrum(event_pollblock *event, void *reference)
{
    int i;
    int got;
    int want;
    int any_ok;

    UNUSED_ARG(event);
    UNUSED_ARG(reference);

    /* Non-blocking mode (enabled once in main() via
       os_args_set_nonblocking) makes os_gbpb_read4() return HONEST
       short-read counts instead of the default blocking mode's silent
       zero-padding to the requested size (see docs/PLAN.md milestone
       5 -- confirmed on real hardware via a sentinel-fill test).
       Accumulate across multiple calls into accum_buf_g until a full
       IQ_BYTES frame is ready, rather than requiring got==IQ_BYTES from
       a single call, which blocking mode never honestly gave anyway.

       Each honest read tends to return only about HALF of what's
       requested (confirmed in milestone 5's sentinel test), so filling
       the last few bytes of a frame can take many more attempts than
       filling the first half -- with a small fixed attempt cap
       (previously BATCH_READS=16), a frame could easily need 1-2 extra
       bytes that don't arrive until the NEXT idle tick, tens of
       milliseconds later. That means the "frame" handed to the FFT
       could be a concatenation of samples from genuinely different
       moments in time -- which would corrupt frequency resolution
       (smearing real signal energy across every bin) while leaving the
       DC bin untouched (it's just a sum, order-independent) -- exactly
       the pattern seen on real hardware: a real ~40dB FM station
       (confirmed working with this same dongle+antenna in SDR# on
       Windows) produced an essentially flat computed spectrum here.
       Non-blocking reads can't hang, so it's safe to loop until a frame
       is genuinely complete OR the stream truly has nothing more
       available right now (got==0), rather than capping at a small
       fixed attempt count. MAX_READ_ATTEMPTS is a generous safety
       bound against a pathological runaway, not a normal-operation
       limit. */
#define MAX_READ_ATTEMPTS 5000
    any_ok = 0;
    for (i = 0; i < MAX_READ_ATTEMPTS; i++) {
        want = IQ_BYTES - accum_fill_g;
        got = os_gbpb_read4(stream_handle_g, accum_buf_g + accum_fill_g, want);
        if (got < 0) {
            debug_reads_bad_g++;
            break;
        }
        if (got == 0) {
            break;
        }
        /* Only count whole I/Q pairs. want is always even (IQ_BYTES and
           accum_fill_g are both kept even by this same rule), but the
           SWI decides how much to actually deliver -- if that "got"
           happens to be odd (very plausible once want stops being a
           round power of two, which milestone 5's sentinel test never
           exercised), accepting it as-is would leave accum_fill_g odd,
           permanently shifting every iq_frame_g[2*i]/[2*i+1] I/Q
           pairing by one byte for the rest of the frame -- silently
           swapping I and Q with the wrong neighbours. That would
           scramble frequency content while leaving the DC sum (order-
           independent) untouched, which matches exactly what real runs
           have shown: real signal present, DC always the same, every
           other bin flat. Dropping a lone trailing byte here (left in
           the buffer to be overwritten next read) costs one sample out
           of many thousands and keeps pairing intact throughout. */
        accum_fill_g += got & ~1;
        if (accum_fill_g < IQ_BYTES) {
            continue;
        }

        {
            int j;
            memcpy(iq_frame_g, accum_buf_g, IQ_BYTES);
            accum_fill_g = 0;
            any_ok = 1;
            debug_reads_ok_g++;
            memcpy(debug_first_bytes_g, iq_frame_g, sizeof(debug_first_bytes_g));
            /* raw byte range across the WHOLE frame, not just the first
               4 bytes -- distinguishes "the ADC genuinely sees almost no
               swing" from "the FFT/scaling math is flattening real
               variation". See the debug_*_g comment above. */
            debug_byte_min_g = 255;
            debug_byte_max_g = 0;
            for (j = 0; j < IQ_BYTES; j++) {
                if (iq_frame_g[j] < debug_byte_min_g) {
                    debug_byte_min_g = iq_frame_g[j];
                }
                if (iq_frame_g[j] > debug_byte_max_g) {
                    debug_byte_max_g = iq_frame_g[j];
                }
            }

            /* FFT this frame and fold it into the running power
               average NOW, every time a frame completes -- which can
               happen many times a second, far faster than the ~5Hz
               display throttle below. Averaging as many frames as
               actually arrive (rather than only the single one that
               happens to be latest when the display updates) is the
               whole point: it's what reduces a single raw FFT
               snapshot's high per-bin variance. See the comment above
               accumulate_frame(). */
            accumulate_frame();
        }
    }

    if (any_ok && Time_Monotonic() >= next_update_time_g) {
        finalize_display();
        Window_ForceRedraw(spectrum_window_g, 0, -WORK_HEIGHT, WORK_WIDTH, 0);
        next_update_time_g = Time_Monotonic() + UPDATE_INTERVAL_CS;
    }

    return FALSE;
}

static BOOL Redraw_spectrum(event_pollblock *event, void *reference)
{
    window_redrawblock r;
    BOOL more;
    int ox, oy;
    int i;

    UNUSED_ARG(event);
    UNUSED_ARG(reference);

    r.window = spectrum_window_g;
    Wimp_RedrawWindow(&r, &more);

    while (more) {
        /* (rect, scroll) are the window's on-screen box and scroll
           offset -- constant for this whole redraw loop, unlike
           cliprect, which changes each iteration. Standard RISC OS
           work-area-to-screen conversion: screen = os_origin + work,
           where os_origin is derived once from rect/scroll. */
        ox = r.rect.min.x - r.scroll.x;
        oy = r.rect.max.y - r.scroll.y;

        Wimp_SetColour((int)colour_BLACK);

        /* Both a fixed 100x100 square AND a fixed 1-wide/WORK_HEIGHT-
           tall rectangle rendered correctly as standalone calls,
           proving drawing/colour/coordinates/thin-width/exact-boundary-
           height are all individually fine. The one thing neither
           isolation test covered: calling GFX_RectangleFill 256 times
           in a tight loop where ~255 of those calls are DEGENERATE
           (bin_height_g[i]==0, since min==max==47 gives near-zero
           height to almost every non-DC bin) -- a zero-height
           rectangle-fill may not be a well-behaved OS_Plot code path,
           and could be corrupting state for later calls in the same
           loop (which would explain why even the one real, non-zero
           bar -- the DC bin -- never showed). Skipping zero-height
           bars costs nothing visually (they're invisible either way)
           and tests this directly. */
        for (i = 0; i < NUM_BINS; i++) {
            if (bin_height_g[i] > 0) {
                GFX_RectangleFill(ox + i * BIN_WIDTH_OS, oy - WORK_HEIGHT,
                                   BIN_WIDTH_OS - 1, bin_height_g[i]);
            }
        }

        /* Diagnostic text was 5 lines tall (added while chasing the
           DeviceFS padding bug, see docs/PLAN.md milestone 5) -- with
           ~56 units needed per line to avoid overlap, that filled the
           ENTIRE window height, leaving no room for the bars it was
           supposed to help debug (confirmed: a real run showed nothing
           but text, "that is the entire window"). The read pipeline is
           now confirmed fixed and working, so this is back to a single
           compact line -- just enough to glance at, not covering the
           actual spectrum. VDU 5 switches text output to plot at the
           graphics cursor (GFX_Move'd position) instead of the text
           cursor; VDU 4 reverts. */
        {
            char line1[48];
            /* dc/h dropped: after DC removal, db[centre] is trivially
               ALWAYS exactly 0 (subtracting the mean and then summing
               the result is 0 by definition, regardless of any real
               signal) -- it was never meaningful new information, a
               diagnosis mistake caught after a wasted round-trip. What
               actually matters: WHERE the frame's strongest (non-DC)
               bin sits relative to the tuned frequency (dead centre).
               Landing consistently within roughly +-10 of centre (the
               ~21-bin span a 200kHz FM signal should occupy at our
               ~9.4kHz/bin resolution) would mean a real station peak IS
               being captured; scattering randomly across all 251
               non-DC bins would mean noise-floor-driven behaviour with
               no real peak found yet. */
            /* pk@ dropped (already confirmed solid at +3 across many
               runs) to make room for real decimal precision -- %.0f
               rounds to the nearest whole dB, which could easily be
               hiding a real but modest gap (e.g. 44.6 vs 45.4) behind
               two identical-looking rounded integers. Getting the true
               numbers beats guessing at another architectural change
               blind. */
            sprintf(line1, "min=%.2f max=%.2f",
                    debug_db_min_g, debug_db_max_g);
            /* Latest real run showed min/max/pk stuck at exactly their
               own startup defaults (0.0/0.0/0) -- consistent with
               finalize_display() (and possibly accumulate_frame())
               never actually running at all, not a math/averaging bug.
               Re-adding ok=/bad= (dropped a few commits back to make
               room) to directly check whether reads are even
               completing frames in this build, before guessing at the
               averaging code again. */
            {
                char line2[32];
                sprintf(line2, "ok=%lu bad=%lu",
                        debug_reads_ok_g, debug_reads_bad_g);
                GFX_VDU(5);
                GFX_Move(ox + 4, oy - 76);
                GFX_Write0(line2);
                GFX_VDU(4);
            }
            GFX_VDU(5);
            GFX_Move(ox + 4, oy - 20);
            GFX_Write0(line1);
            GFX_VDU(4);
        }

        Wimp_GetRectangle(&r, &more);
    }
    return TRUE;
}

static BOOL Close_spectrum(event_pollblock *event, void *reference)
{
    UNUSED_ARG(event);
    UNUSED_ARG(reference);
    cleanup_and_exit();
    return TRUE; /* unreached */
}

static BOOL Quit_message(event_pollblock *event, void *reference)
{
    if (event->data.message.header.action == message_QUIT) {
        cleanup_and_exit();
    }
    return FALSE;
}

/* Mirrors window_block field-for-field (same 88-byte layout Wimp_CreateWindow
   expects -- verified offset by offset against the real block layout: 0
   screenrect, 16 scroll, 24 behind, 28 flags, 32 colours, 40 workarearect,
   56 titleflags, 60 workflags, 64 spritearea, 68 minsize, 72 title, 84
   numicons), but WITHOUT window_block's own `colours` field
   (wimp_colourflags), which mixes `unsigned char` fields with `unsigned
   int` bitfields in the same struct -- a combination where Norcroft can
   pad the union out past its intended 8 bytes to fit the bitfield's
   alignment, silently shifting every field after `colours` relative to
   what the real Wimp SWI expects. Confirmed the hard way: window_block
   crashed Wimp_CreateWindow with a data abort deep in the Wimp's own
   processing of the block, and rewriting only the VALUES (still via
   window_block's .colours field) did not fix it -- same crash, same
   address, because the union's SIZE was the actual problem, not which
   member was used to write into it. See docs/PLAN.md. Every other field
   here reuses window_flags/icon_flags, which are safe: homogeneous
   unsigned-int bitfields matching their own .value alias exactly, with
   no mixed-type padding risk. */
typedef struct {
    wimp_box      screenrect;
    wimp_point    scroll;
    int           behind;
    window_flags  flags;
    unsigned char title_fore, title_back, work_fore, work_back;
    unsigned char scroll_outer, scroll_inner, title_focus, colour_extra;
    wimp_box      workarearect;
    icon_flags    titleflags;
    icon_flags    workflags;
    void          *spritearea;
    unsigned short minsize_x, minsize_y;
    char          title_text[12];
    unsigned int  numicons;
} raw_window_block;

static window_handle create_spectrum_window(void)
{
    raw_window_block rwb;
    window_handle win;
    os_error *err;

    memset(&rwb, 0, sizeof(rwb));

    rwb.screenrect.min.x = 200;
    rwb.screenrect.min.y = 200;
    rwb.screenrect.max.x = 200 + WORK_WIDTH;
    rwb.screenrect.max.y = 200 + WORK_HEIGHT;
    rwb.scroll.x = 0;
    rwb.scroll.y = 0;
    rwb.behind = -1;

    rwb.flags.data.moveable = 1;
    rwb.flags.data.titlebar = 1;
    rwb.flags.data.closeicon = 1;
    rwb.flags.data.newflags = 1;

    rwb.title_fore = colour_BLACK;
    rwb.title_back = colour_LIGHT_BLUE;
    rwb.work_fore = colour_BLACK;
    rwb.work_back = colour_WHITE;
    rwb.scroll_outer = colour_GREY3;
    rwb.scroll_inner = colour_WHITE;
    rwb.title_focus = colour_LIGHT_BLUE;
    rwb.colour_extra = 0;

    rwb.workarearect.min.x = 0;
    rwb.workarearect.min.y = -WORK_HEIGHT;
    rwb.workarearect.max.x = WORK_WIDTH;
    rwb.workarearect.max.y = 0;

    rwb.titleflags.data.text = 1;

    rwb.spritearea = NULL;
    rwb.minsize_x = 0;
    rwb.minsize_y = 0;

    strcpy(rwb.title_text, "RTLSDRView");
    rwb.numicons = 0;

    err = Wimp_CreateWindow((window_block *)&rwb, &win);
    if (err != NULL) {
        report_and_die(err->errmess);
    }
    return win;
}

int main(void)
{
    int n;
    int rc;
    r82xx_t tuner;
    char path[64];

    Event_Initialise("RTLSDRView");

    n = find_device();
    if (n < 0) {
        report_and_die("No RTL-SDR device found. Run !RTLSDR first to "
                        "confirm the dongle is detected.");
    }
    sprintf(device_name_g, "usb%d", n);

    rtlsdr_init_baseband(device_name_g);

    if (rtlsdr_probe_tuner(device_name_g) != 2) {
        report_and_die("R828D tuner not found -- see !RTLSDR's "
                        "diagnostic output for details.");
    }

    rtlsdr_demod_write_reg(device_name_g, 1, 0x01, 0x18, 1); /* enable I2C repeater */
    rc = rtlsdr_tuner_postinit(device_name_g);
    if (rc == 0) {
        rc = r82xx_init(&tuner, device_name_g);
    }
    if (rc == 0) {
        rc = r82xx_set_freq(&tuner, 97400000UL); /* 97.4MHz, local FM broadcast */
    }
    if (rc == 0 && tuner.has_lock) {
        /* AGC (upstream's own default -- see R82XX.h) hasn't made the
           station stand out from the noise floor in several real runs
           now that the read/render pipeline is confirmed correct.
           Testing manual maximum gain as a direct, well-grounded next
           step (ported from real upstream source, not guessed -- see
           docs/PLAN.md) rather than continuing to assume AGC alone is
           sufficient. Needs the I2C repeater still enabled, same as
           r82xx_set_freq() above -- must run before it's disabled
           below. */
        rc = r82xx_set_gain_max(&tuner);
    }
    rtlsdr_demod_write_reg(device_name_g, 1, 0x01, 0x10, 1); /* disable I2C repeater */
    if (rc != 0 || !tuner.has_lock) {
        report_and_die("Tuner init/tune to 97.4MHz failed -- see "
                        "!RTLSDR's diagnostic output for details.");
    }

    if (rtlsdr_set_sample_rate(device_name_g, 2400000UL) != 0) {
        report_and_die("rtlsdr_set_sample_rate() failed.");
    }

    rtlsdr_reset_buffer(device_name_g);

    sprintf(path, "devices#endpoint%d;interface%d;bulk;usbtimeout2000:%s",
            RTLSDR_BULK_ENDPOINT, RTLSDR_BULK_INTERFACE, device_name_g);
    stream_handle_g = os_find_open(path);
    if (stream_handle_g == 0) {
        report_and_die("Could not open the bulk endpoint stream.");
    }
    if (os_args_set_nonblocking(stream_handle_g, 1) != 0) {
        report_and_die("Could not enable non-blocking mode on the "
                        "bulk stream -- see docs/PLAN.md milestone 5.");
    }

    spectrum_window_g = create_spectrum_window();
    Window_Show(spectrum_window_g, open_CENTERED);

    Event_Claim(event_REDRAW, spectrum_window_g, event_ANY, Redraw_spectrum, NULL);
    Event_Claim(event_CLOSE, spectrum_window_g, event_ANY, Close_spectrum, NULL);
    Event_Claim(event_USERMESSAGE, event_ANY, event_ANY, Quit_message, NULL);
    Event_Claim(event_NULL, event_ANY, event_ANY, Null_spectrum, NULL);

    next_update_time_g = Time_Monotonic();

    while (TRUE) {
        Event_Poll();
    }

    return 0; /* unreached */
}
